# Generated by Django 4.2.24 on 2025-10-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('wave_direction', models.FloatField(blank=True, null=True)),
                ('wave_period', models.FloatField(blank=True, null=True)),
                ('wave_height', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField(blank=True, null=True)),
                ('current_speed', models.FloatField(blank=True, null=True)),
                ('wind_wave_height', models.FloatField(blank=True, null=True)),
                ('sea_level', models.FloatField(blank=True, null=True)),
                ('wave_onshore', models.FloatField(blank=True, null=True)),
                ('wind_onshore', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location_name', 'timestamp'], name='forecast_we_locatio_61a016_idx'), models.Index(fields=['timestamp'], name='forecast_we_timesta_9a39bc_idx')],
                'unique_together': {('location_name', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SurfRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('hoog', models.FloatField(blank=True, null=True)),
                ('clean', models.FloatField(blank=True, null=True)),
                ('krachtig', models.FloatField(blank=True, null=True)),
                ('stijl', models.FloatField(blank=True, null=True)),
                ('stroming', models.FloatField(blank=True, null=True)),
                ('windy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['location_name', 'timestamp'], name='forecast_su_locatio_cd6997_idx')],
                'unique_together': {('location_name', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SurfFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('spot', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='forecast_su_timesta_88dc86_idx'), models.Index(fields=['spot'], name='forecast_su_spot_4ee51d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['cache_key'], name='forecast_si_cache_k_89f30e_idx'), models.Index(fields=['expires_at'], name='forecast_si_expires_8831b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuoyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buoy_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('wave_height', models.FloatField(blank=True, null=True)),
                ('wave_period', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['buoy_name', 'timestamp'], name='forecast_bu_buoy_na_019c79_idx')],
                'unique_together': {('buoy_name', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('spot', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('alert_timestamp', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='forecast_al_timesta_e0f96c_idx'), models.Index(fields=['spot'], name='forecast_al_spot_1501b6_idx')],
            },
        ),
    ]
